#  ░█████╗░██████╗░██╗░░░██╗░░░░░██╗░█████╗░██╗███╗░░██╗
#  ██╔══██╗██╔══██╗╚██╗░██╔╝░░░░░██║██╔══██╗██║████╗░██║
#  ██║░░╚═╝██████╔╝░╚████╔╝░░░░░░██║██║░░██║██║██╔██╗██║
#  ██║░░██╗██╔══██╗░░╚██╔╝░░██╗░░██║██║░░██║██║██║╚████║
#  ╚█████╔╝██║░░██║░░░██║░░░╚█████╔╝╚█████╔╝██║██║░╚███║
#  ░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░░╚════╝░╚═╝╚═╝░░╚══╝
#          By TheBoykissOld v1.0

join-message: "&7[&a+&7] &a%playername%"
sound-join: ENTITY_PLAYER_LEVELUP